name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .
        continue-on-error: true # Continue with the pipeline even if there are linting errors

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # Add additional steps for build and deployment as needed
